roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.postgresql
    source: https://galaxy.ansible.com
  - name: davidwittman.redis
    source: https://galaxy.ansible.com
  - name: lae.netbox
    source: https://galaxy.ansible.com
 
